version: 2.1

orbs:
    python: circleci/python@1.5.0
    docker: circleci/docker@1.5.0

jobs:
    build-and-test: 
        
        steps:
            - checkout
            - python/install-packages:
                pkg-manager: pip

            - run:
                name: Run tests
                command: pytest

            - run:
                name: linting PEP8
                command: flake8
            
             # un environnement distant sera créé et votre conteneur primaire sera configuré
            - setup_remote_docker
        
    deploy-docker:

        docker:
            - image: cimg/python:3.10.2
              auth:
                username: $DOCKERHUB_USERNAME
                password: $DOCKERHUB_PASSWOR
        
        steps:
            - checkout

            - run: 
                name: build image
                command: docker build -t docker run -p 8000:8000 oussamaabid82/letting:latest .
            
            - run:
                # Pousse l'image Docker vers Docker Hub. 
                name: Push to Docker Hub
                command: |
                    docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                    docker tag oussamaabid82/letting:latest oussamaabid82/letting:$CIRCLE_SHA1
                    docker push oussamaabid82/letting:$CIRCLE_SHA1

    deploy-heroku:
        machine: true
        steps:
            - checkout
            - run:
                name: Build and push Docker image to Heroku
                command: |
                    sudo curl https://cli-assets.heroku.com/install.sh | sh
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web


workflows:
    sample: 
        jobs:
            - build-and-test
            - deploy-docker
