version: 2.1

orbs:
    python: circleci/python@1.5.0
    docker: circleci/docker@1.5.0
    heroku: circleci/heroku@1.2.6

jobs:

    build-and-test:
        executor: python/default
        steps:
            - checkout
            - python/install-packages:
                pkg-manager: pip

            - run:
                name: Run tests
                command: pytest

            - run:
                name: linting PEP8
                command: flake8

    image-docker:

        docker:
            - image: cimg/python:3.9.13
              auth:
                username: $DOCKER_LOGIN
                password: $DOCKER_PASSWORD
        
        steps:
            - checkout
            
            - setup_remote_docker:
                version: 20.10.14
                docker_layer_caching: true

            - run: 
                name: build Docker image
                command: |
                    docker build -t letting:latest .
                    docker push letting:latest
            
            - run:
                # Pousse l'image Docker vers Docker Hub. 
                name: Push to Docker Hub
                command: |
                    docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
                    docker tag oussamaabid82/lettings:latest oussamaabid82/letting:$CIRCLE_SHA1
                    docker push oussamaabid82/letting:$CIRCLE_SHA1

    deploy-heroku:
        machine: true
        steps:
            - checkout
            - run:
                name: Build and push Docker image to Heroku
                command: |
                    sudo curl https://cli-assets.heroku.com/install.sh | sh
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web

workflows:
    sample: 
        jobs:
            - build-and-test
            - image-docker
            - deploy-heroku
