version: 2.1

orbs:
    python: circleci/python@1.5.0
    docker: circleci/docker@1.5.0
    heroku: circleci/heroku@1.2.6

jobs:

    # Parti CI integrartion continue
    build-and-test:
        executor: python/default
        steps:
            - checkout
            # MAJ de pip
            - run:
                name: update pip
                command: python -m pip install --upgrade pip
            
            # installation des dépendance
            - python/install-packages:
                pkg-manager: pip

            # Execution des test
            - run:
                name: Run tests
                command: pytest

            #Vérification de la qualité du code
            - run:
                name: linting PEP8
                command: flake8

    image-docker:

        # Authentification à Docker
        docker:
            - image: cimg/python:3.9.13
              auth:
                username: $DOCKER_LOGIN
                password: $DOCKER_PASSWORD
        
        steps:
            - checkout
            
            - setup_remote_docker:
                version: 20.10.14
                docker_layer_caching: true

            # Création de l'image Docker
            - run: 
                name: build Docker image
                command: |
                    docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
                    docker build -t $DOCKER_LOGIN/$IMAGE_NAME:latest .
                    docker push $DOCKER_LOGIN/$IMAGE_NAME:latest
            
            # Pousse l'image Docker vers Docker Hub.
            - run: 
                name: Push to Docker Hub
                command: |
                    docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
                    docker tag $DOCKER_LOGIN/$IMAGE_NAME:latest $DOCKER_LOGIN/$IMAGE_NAME:$CIRCLE_SHA1
                    docker push $DOCKER_LOGIN/$IMAGE_NAME:$CIRCLE_SHA1
    
    # Parti CI integrartion continue
    deploy-heroku:
        machine: true
        steps:
            - checkout
            # Pousser l'image Docker sur Heroku
            - run:
                name: Build and push Docker image to Heroku
                command: |
                    sudo curl https://cli-assets.heroku.com/install.sh | sh
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DEBUG=0 -a ${HEROKU_APP_NAME}
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set PORT=8000 -a ${HEROKU_APP_NAME}
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${DJANGO_SECRET_KEY} -a ${HEROKU_APP_NAME}
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SENTRY_DSN=${SENTRY_DSN} -a ${HEROKU_APP_NAME}
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
    sample: 
        jobs:
            - build-and-test
            - image-docker
            - deploy-heroku
