# Generated by Django 3.0 on 2022-06-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20220608_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
